Auth with devise
realvint/test-guru pull request #10
Opened 2021-08-20 22:27 UTC by realvint

1. Реализуйте аутентификацию в проекте при помощи библиотеки Devise
2. Сделайте управление ресурсами вопросов и ответов доступным только для администраторов
3. С помощью хэлпера Devise реализуйте перенаправление администраторов на страницу /admin/tests после логина
4. При создании нового теста администратором назначайте его в качестве автора теста

Усложненное задание:

При регистрации пользователя запрашивать его имя и фамилию и после входа, выводить флэш-сообщение "Привет, <имя пользователя>!"

2021-08-21 06:46 UTC, VidgarVii requested changes

2021-08-21 06:46 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +    flash[:notice] = "Привет, #{user.name} #{user.surname}!"
это очень плохой сайд эффект
данный метод отвечает только за формироваия урла после логина юзера. Больше ни чео
Флеш сообщение надо устанавливать в том экшане где происходит логин.
Чтобы выполнить это ДЗ. надо переоределить экшен

2021-08-21 06:46 UTC, VidgarVii commented on db/migrate/20210820131351_add_surname_and_type_attibutes_to_users.rb
> +end
в это ПР вся работу над таблицей уже происходит в миграции db/migrate/20210819103044_add_devise_to_users.rb
Зачем создавать еще одну, когда можно всё сделать в одной миграции????

2021-08-22 14:39 UTC, VidgarVii commented on db/migrate/20210819103044_add_devise_to_users.rb
> +
при откате миграции эти колонки должны удалиться

2021-08-22 14:53 UTC, realvint commented on db/migrate/20210819103044_add_devise_to_users.rb
> +
Исправил

2021-08-22 14:57 UTC, merged