add gists by github api
realvint/test-guru pull request #13
Opened 2021-08-28 23:12 UTC by realvint

1. Используйте официальный клиент GitHub Octokit
2. Выводите ссылку на созданный gist во flash сообщении
3. Добавьте интернационализацию в сервис GistQuestionService
4. Добавьте модель Gist. У администратора сделайте вывод таблицы всех созданных gist. Таблица должна содержать обязательные колонки:
  Вопрос. Отображаются первые 25 символов тела вопроса в виде ссылки. По клике на ссылку отображается страница вопроса (действие show)
  Gist URL. Отображается хэш созданного gist в виде ссылки
  Пользователь. Отображается email пользователя который создал gist

2021-08-29 10:15 UTC, VidgarVii requested changes

2021-08-29 10:15 UTC, VidgarVii commented on Gemfile
> +gem 'faraday'
faraday больше не будет использоватьсяю Его стоит удалить

2021-08-29 10:15 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +  def gist
Gist это модель. Значит согласно rails way для создания ресурса  и записи в БД объекта Gist должен быть отдельный контроллер с экшеном create

2021-08-29 10:15 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +    result.call
можнос сократить строчку.
GistQuestionService.new(@test_passage.current_question).call

2021-08-29 10:15 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +  end
сейчас этот класс выглядит так, что можно вызывать метод url и success? сразу после порождения экземпляра класса. Но это приведет к ошибкам. 
Чтобы этого не было надо сделать так, чтобы метод call возвращал такой объект, который бы содержал результат запроса со всеми нужными данными и методами.
можно воспользоваться структурой Struct

2021-08-29 10:15 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +  end
[@question.body, *@question.answers.pluck(:title)].join("\n")

2021-08-29 10:20 UTC, realvint commented on Gemfile
> +gem 'faraday'
Удалил

2021-08-29 10:26 UTC, realvint commented on app/services/gist_question_service.rb
> +  end
Поправил

2021-08-29 13:57 UTC, realvint commented on app/services/gist_question_service.rb
> +  end
Refactored

2021-08-29 13:57 UTC, realvint commented on app/controllers/test_passages_controller.rb
> +    result.call
Сделано

2021-08-29 13:57 UTC, realvint commented on app/controllers/test_passages_controller.rb
> +  def gist
Вынес логику в отдельный контроллер gists_controller

2021-08-31 06:54 UTC, VidgarVii commented on Gemfile.lock
> +    faraday (1.4.2)
надо запустить bundle

2021-08-31 06:54 UTC, VidgarVii commented on app/controllers/gists_controller.rb
> +      current_user.gists.create(question: test_passage.current_question, url: result.url)
тут стоит использовать create! чтобы убедиться. что данные записываются корректно. (Проверка самого себя)
а затем уже выводить flash

2021-08-31 07:04 UTC, realvint commented on app/controllers/gists_controller.rb
> +      current_user.gists.create(question: test_passage.current_question, url: result.url)
Поправил

2021-08-31 07:04 UTC, realvint commented on Gemfile.lock
> +    faraday (1.4.2)
Запустил

2021-08-31 07:11 UTC, merged